export const SERVICE_NAME = 'gateway';

export const SERVICE_QUEUE_NAME = `${SERVICE_NAME}-queue`;

export enum ConfigVariables {
  REQUIRED_ENVIRONMENT_VARIABLE = 'REQUIRED_ENVIRONMENT_VARIABLE',
  CACHE_URL = 'CACHE_URL',
  DB_URL = 'DB_URL',
  RABBITMQ_URL = 'RABBITMQ_URL',
}
